name: teja_http_json
description: Write concise JSON API clients
version: 0.1.5
author: Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://github.com/tejainece/teja_http_json

documentation:

environment:
  sdk: '>=1.19.0 <2.0.0'

dependencies:
  http: '>=0.11.3 <0.12.0'
  jaguar_serializer: '>=0.3.8 <0.4.0'

dev_dependencies:
  jaguar: '>=0.5.8 <0.6.0'
  jaguar_reflect: '>=0.5.1 <0.6.0'
  test: '>=0.12.19+1 <0.13.0'
