name: teja_http_json
description: A small utility library over Dart's package:http to make JSON request simpler
version: 0.0.1
author: Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://github.com/tejainece/teja_http_json

environment:
  sdk: '>=1.19.0 <2.0.0'

#dependencies:
#  lib_name: any

dev_dependencies:
  jaguar: '>=0.4.2 <0.5.0'
  jaguar_reflect: '>=0.4.2 <0.5.0'
  test: '>=0.12.19+1 <0.13.0'
