name: jaguar_client
description: Write concise JSON API clients
version: 0.1.4
author: Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_client

documentation:

environment:
  sdk: '>=1.19.0 <2.0.0'

dependencies:
  http: '>=0.11.3 <0.12.0'
  jaguar_serializer: ^0.3.12
  jaguar_common: ^0.2.1
  auth_header: ^0.0.3
  client_cookie: ^0.1.0

dev_dependencies:
  jaguar: ^0.6.5
  test: '>=0.12.19+1 <0.13.0'
