name: jaguar_client
description: Write concise JSON API clients
version: 2.0.2
author: Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_client

documentation:

environment:
  sdk: '>=1.19.0 <2.0.0'

dependencies:
  http: '>=0.11.3 <0.12.0'
  jaguar_serializer: ^1.0.0-dev7
  jaguar_common: ^0.2.1
  auth_header: ^0.0.3
  client_cookie: ^2.1.2
  jaguar_resty: ^2.4.2
  async: ^2.0.7

dev_dependencies:
  jaguar: ^2.0.2
  test: '>=0.12.19+1 <0.13.0'
  jaguar_reflect:
